# Generated by Django 5.1.2 on 2024-11-08 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'permissions': [('can_access_page_stopwatch', 'Can access stopwatch page'), ('can_access_page_profile', 'Can access profile page')]},
        ),
    ]
